### ISSUE TITLE
Make the border colour configurable

### ISSUE THREAD

**Issue by waimus** [yilozt/mutter#1]
Hi, 

I think the grey border colour could be configurable. The current value (0.65 white) looks fine in light themes, but looks too bright on the dark themes. A value of 0.35 looks better for dark themes. So I thought about making it configurable within the range of white to black.

So I did play around with your mutter-rounded patch and added a border-brightness key to configure the border colour. It simply changes the border colour in `src/shader.h` file. Here's my commit https://github.com/waimus/mutter/commit/e5d9671fdf3ad8e4fba0b0265c451c68d1f1767e.

If you like it, I will be making a PR here.

I have considered making it configurable to input colours (i.e. hex code colours), but I think a colourful border is a bit too wild. So I only did this so far.

Thank you.

**Comment by nine7nine** [comment]
@yilozt - I've also been using this code - it's quite good and something users will definitely want; as the white border is a bit intense. personally i set the border-brightness to 12.

**Comment by yilozt** [comment]
@waimus  - I am sorry that I have not receive notifications because I have forgot watching this repository before. 

Thanks for your contribution, I will merge it if you open a pull request.

**Comment by waimus** [comment]
Thank you, I did
