### ISSUE TITLE
New windows: Blur vs. Animation transition ordering on new windows

### ISSUE THREAD

**Issue by nine7nine** [yilozt/mutter#4]
Hey @yilozt 

So i've been tinkering aorund with the blur code and while i was able to fix most of the blur artifacts in my previous patch -- I'm having trouble getting the blur on new windows to appear AFTER the open effect is complete...

I'm not sure exactly what the problem is -- i was wondering if you could have a look? the easiest way to demonstrate the issue; install the 'Impatience' gnome extension, set the animation speed to the slowest (2sec), then open a new app window...  you will see it paints the blur first, which isn't what we want -- the blur shouldn't be painted until after the effect is complete and the window is fully drawn on the screen.

I thought a similar bit of code would work like i did for the unminimize case, but for whatever reason, it didn't seem to work. I was hoping you might see if you are able to fix it? you likely understand the code a bit better.

thx

**Comment by yilozt** [comment]
Blur actor should appears after transition finish when window opening, via commit [a4a4829](https://github.com/yilozt/mutter/commit/a4a4829b136f521b4a422b6091cea86a40d37e3d)

**Comment by nine7nine** [comment]
verified here too. yup, that fixes it and i see why my code wasn't quite write too.

this is nice. great to have the blurred artifacts / ordering issues solved. looks much nicer.

closing. :-)
