### ISSUE TITLE
Workspaces - shows blurred windows from other workspace(s)

### ISSUE THREAD

**Issue by nine7nine** [yilozt/mutter#5]
I think this bug may have just been introduced. but when switching workspaces, there is blurred windows from the previous workspace.

i think this may have been introduced with the fixing of blurred windows on new windows, not positive though.

**Comment by yilozt** [comment]
I found `on_visible_changed()` callback that  removed at [a4a4829](https://github.com/yilozt/mutter/commit/a4a4829b136f521b4a422b6091cea86a40d37e3d) is used to hide / show blur actor when switching workspace, so I add it back.

**Comment by yilozt** [comment]
I also change some logic in `meta_window_actor_show_blur()`, now blur actor should be shown after transition finish when opening window.

**Comment by nine7nine** [comment]
I just took a look / rebuilt mutter. looks great. 

this actually makes more sense. i should've probably done something similar to begin with -- but i wasn't very familiar with the code in question.

I would say the blur code is now fixed, as far as ordering issues with animations. looks like that was the last issue/bug. :+1:
